const product=[
    {
      id:0,
      img:"homeimage/i2.jpg",
      title:"Panjabi",
      price:700,
    },
    {
      id:1,
      img:"homeimage/i3.jpg",
      title:"Panjabi",
      price:600,
    },
    {
      id:2,
      img:"homeimage/i4.jpg",
      title:"Panjabi",
      price:1000,
    },
    {
      id:3,
      img:"homeimage/i5.jpg",
      title:"Panjabi",
      price:900,
    },
    {
      id:4,
      img:"homeimage/i8.jpg",
      title:"Panjabi",
      price:800,
    },
    {
        id:5,
        img:"homeimage/i3.jpg",
        title:"Panjabi",
        price:300,
      }
  ]